version: '3.8'

services:
  personal-site:
    build: ./personal-website
    container_name: personal-site
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - project-net

  todo-app:
    image: docker.io/amir20/dozzle-todo:latest
    container_name: todo-app
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - project-net

networks:
  project-net:
    driver: bridge
