version: '3.8'

services:
  personal-site:
    build: ./personal-website
    container_name: personal-site
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - project-net

  todo-app:
    image: amir20/todo-list-app:latest
    container_name: todo-app
    ports:
      - "8081:3000"
    restart: unless-stopped
    networks:
      - project-net
    depends_on:
      - mongo # 确保 MongoDB 先启动
    environment:
      - MONGO_URL=mongodb://mongo:27017/todoapp # 连接 MongoDB

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - todo-db:/data/db
    networks:
      - project-net

networks:
  project-net:
    driver: bridge

volumes:
  todo-db:
